services:
  - type: web
    name: stirling-pdf-custom # Choisissez un nom pour votre service sur Render (personnalisé)
    dockerfilePath: Dockerfile
    port: 8080
    healthCheckPath: /  #  Chemin pour le health check (peut être ajusté si nécessaire)
    plan: free # Ou un plan payant selon vos besoins
