services:
  - type: web
    name: stirling-pdf
    dockerfile: Dockerfile
    plan: free # ou 'starter'/'professional' selon vos besoins
    envVars:
      - key: VERSION_TAG
        value: your_version_here # Remplacez par votre version (ex: v1.0.0)
      - key: DOCKER_ENABLE_SECURITY
        value: "false"
      - key: ENDPOINTS_GROUPS_TO_REMOVE
        value: "CLI"
    build:
      args:
        VERSION_TAG: ${VERSION_TAG}
