services:
  - type: web
    name: stirling-pdf
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DOCKER_ENABLE_SECURITY
        value: "false"  # Désactive les vérifications de sécurité Docker
      - key: VERSION_TAG
        value: "0.39.0"  # Version fixe pour la compatibilité
      - key: INSTALL_BOOK_AND_ADVANCED_HTML
        value: "true"  # Active les fonctionnalités supplémentaires
    buildCommand: |
      docker build -t stirling-pdf . 
    dockerCommand: /usr/src/app/run.sh --port 8080
