services:
  - type: web
    runtime: docker  # Indique explicitement que c'est un runtime Docker
    name: stirling-pdf-custom  # Choisissez un nom pour votre service sur Render (personnalisé)
    dockerfilePath: Dockerfile
    port: 8080 # Réinsérez le port, il était manquant dans votre dernier extrait.
    healthCheckPath: /  #  Chemin pour le health check (peut être ajusté si nécessaire)
    plan: free # Ou un plan payant selon vos besoins
Use code with caution.
