services:
  - type: web
    name: stirling-pdf
    runtime: docker  # Utilisez runtime: docker pour spécifier un déploiement Docker
    plan: free # Changer pour 'starter' ou 'standard' pour la production
    region: frankfurt # Choisir la région souhaitée
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_ENVIRONMENT
        value: production
      # Ajouter d'autres variables si nécessaire (ex: API keys, configurations)
      # - key: ALLOWED_FILE_SIZES
      # - value: "25"
